from task_2.domain.usecases.eda_plots_usecase import EdaPlotsUseCase
from task_2.domain.usecases.stationarity_test_usecase import StationarityTestUseCase
from task_2.domain.usecases.feature_engineering_usecase import FeatureEngineeringUseCase
from task_2.domain.usecases.data_cleaning_usecase import DataCleaningUseCase
